// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExams = `-- name: CountExams :one
SELECT COUNT(*) FROM exams WHERE deleted_at IS NULL
`

func (q *Queries) CountExams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExamsBySubject = `-- name: CountExamsBySubject :one
SELECT COUNT(*) FROM exams
WHERE subject_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExamsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedExamsBySubject = `-- name: CountPublishedExamsBySubject :one
SELECT COUNT(*) FROM exams
WHERE subject_id = $1 AND deleted_at IS NULL AND status = 'PUBLISHED'
`

func (q *Queries) CountPublishedExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedExamsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchExams = `-- name: CountSearchExams :one
SELECT COUNT(*) FROM exams 
WHERE (title ILIKE '%' || $1::text || '%' OR description ILIKE '%' || $1::text || '%')
AND deleted_at IS NULL
`

func (q *Queries) CountSearchExams(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchExams, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchExamsBySubject = `-- name: CountSearchExamsBySubject :one
SELECT COUNT(*) FROM exams 
WHERE subject_id = $1
AND (title ILIKE '%' || $2::text || '%' OR description ILIKE '%' || $2::text || '%')
AND deleted_at IS NULL
`

type CountSearchExamsBySubjectParams struct {
	SubjectID uuid.NullUUID `json:"subject_id"`
	Column2   string        `json:"column_2"`
}

func (q *Queries) CountSearchExamsBySubject(ctx context.Context, arg CountSearchExamsBySubjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchExamsBySubject, arg.SubjectID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubmittedAttemptsBySubjectForStudent = `-- name: CountSubmittedAttemptsBySubjectForStudent :one
SELECT COUNT(DISTINCT ea.exam_id)
FROM exam_attempts ea
JOIN exams e ON ea.exam_id = e.id
WHERE e.subject_id = $1
  AND ea.student_id = $2
  AND ea.status IN ('SUBMITTED', 'GRADED')
  AND e.deleted_at IS NULL
`

type CountSubmittedAttemptsBySubjectForStudentParams struct {
	SubjectID uuid.NullUUID `json:"subject_id"`
	StudentID uuid.NullUUID `json:"student_id"`
}

func (q *Queries) CountSubmittedAttemptsBySubjectForStudent(ctx context.Context, arg CountSubmittedAttemptsBySubjectForStudentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmittedAttemptsBySubjectForStudent, arg.SubjectID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExam = `-- name: CreateExam :one
INSERT INTO exams (subject_id, title, description, total_marks, status, created_by)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at
`

type CreateExamParams struct {
	SubjectID   uuid.NullUUID  `json:"subject_id"`
	Title       string         `json:"title"`
	Description *string        `json:"description"`
	TotalMarks  int32          `json:"total_marks"`
	Status      ExamStatusType `json:"status"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, createExam,
		arg.SubjectID,
		arg.Title,
		arg.Description,
		arg.TotalMarks,
		arg.Status,
		arg.CreatedBy,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.TotalMarks,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttemptByExamAndStudent = `-- name: GetAttemptByExamAndStudent :one
SELECT id, exam_id, student_id, started_at, submitted_at, score, status, created_at FROM exam_attempts
WHERE exam_id = $1 AND student_id = $2
ORDER BY started_at DESC
LIMIT 1
`

type GetAttemptByExamAndStudentParams struct {
	ExamID    uuid.NullUUID `json:"exam_id"`
	StudentID uuid.NullUUID `json:"student_id"`
}

func (q *Queries) GetAttemptByExamAndStudent(ctx context.Context, arg GetAttemptByExamAndStudentParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByExamAndStudent, arg.ExamID, arg.StudentID)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, exam_id, student_id, started_at, submitted_at, score, status, created_at FROM exam_attempts WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getExamByID = `-- name: GetExamByID :one
SELECT id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at FROM exams WHERE id = $1
`

func (q *Queries) GetExamByID(ctx context.Context, id uuid.UUID) (Exam, error) {
	row := q.db.QueryRow(ctx, getExamByID, id)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.TotalMarks,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllExams = `-- name: ListAllExams :many
SELECT id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at FROM exams WHERE deleted_at IS NULL ORDER BY created_at DESC, id ASC LIMIT $1 OFFSET $2
`

type ListAllExamsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllExams(ctx context.Context, arg ListAllExamsParams) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listAllExams, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.TotalMarks,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersByAttempt = `-- name: ListAnswersByAttempt :many
SELECT id, attempt_id, question_id, selected_choice_id, is_correct, answered_at FROM student_answers WHERE attempt_id = $1
`

func (q *Queries) ListAnswersByAttempt(ctx context.Context, attemptID uuid.NullUUID) ([]StudentAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentAnswer
	for rows.Next() {
		var i StudentAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.SelectedChoiceID,
			&i.IsCorrect,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByStudent = `-- name: ListAttemptsByStudent :many
SELECT id, exam_id, student_id, started_at, submitted_at, score, status, created_at FROM exam_attempts WHERE student_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListAttemptsByStudent(ctx context.Context, studentID uuid.NullUUID) ([]ExamAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExamAttempt
	for rows.Next() {
		var i ExamAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.StudentID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsBySubject = `-- name: ListExamsBySubject :many
SELECT id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at FROM exams WHERE subject_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExamsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.TotalMarks,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsCreatedBy = `-- name: ListExamsCreatedBy :many
SELECT id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at FROM exams 
WHERE created_by = $1 AND deleted_at IS NULL 
ORDER BY created_at DESC
`

func (q *Queries) ListExamsCreatedBy(ctx context.Context, createdBy uuid.NullUUID) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExamsCreatedBy, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.TotalMarks,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsForStudent = `-- name: ListExamsForStudent :many
SELECT e.id, e.subject_id, e.title, e.description, e.total_marks, e.status, e.created_by, e.created_at, e.updated_at, e.deleted_at 
FROM exams e
JOIN subject_students ss ON e.subject_id = ss.subject_id
WHERE ss.student_id = $1 AND e.deleted_at IS NULL AND ss.deleted_at IS NULL
ORDER BY e.created_at DESC
`

func (q *Queries) ListExamsForStudent(ctx context.Context, studentID uuid.UUID) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExamsForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.TotalMarks,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAnswer = `-- name: SaveAnswer :one
INSERT INTO student_answers (attempt_id, question_id, selected_choice_id, is_correct)
VALUES ($1, $2, $3, $4)
RETURNING id, attempt_id, question_id, selected_choice_id, is_correct, answered_at
`

type SaveAnswerParams struct {
	AttemptID        uuid.NullUUID `json:"attempt_id"`
	QuestionID       uuid.NullUUID `json:"question_id"`
	SelectedChoiceID uuid.NullUUID `json:"selected_choice_id"`
	IsCorrect        pgtype.Bool   `json:"is_correct"`
}

func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) (StudentAnswer, error) {
	row := q.db.QueryRow(ctx, saveAnswer,
		arg.AttemptID,
		arg.QuestionID,
		arg.SelectedChoiceID,
		arg.IsCorrect,
	)
	var i StudentAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.SelectedChoiceID,
		&i.IsCorrect,
		&i.AnsweredAt,
	)
	return i, err
}

const searchExams = `-- name: SearchExams :many
SELECT id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at FROM exams 
WHERE (title ILIKE '%' || $1::text || '%' OR description ILIKE '%' || $1::text || '%')
AND deleted_at IS NULL
ORDER BY created_at DESC, id ASC
LIMIT $2 OFFSET $3
`

type SearchExamsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchExams(ctx context.Context, arg SearchExamsParams) ([]Exam, error) {
	rows, err := q.db.Query(ctx, searchExams, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.TotalMarks,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchExamsBySubject = `-- name: SearchExamsBySubject :many
SELECT id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at FROM exams 
WHERE subject_id = $1
AND (title ILIKE '%' || $2::text || '%' OR description ILIKE '%' || $2::text || '%')
AND deleted_at IS NULL
ORDER BY created_at DESC, id ASC
LIMIT $3 OFFSET $4
`

type SearchExamsBySubjectParams struct {
	SubjectID uuid.NullUUID `json:"subject_id"`
	Column2   string        `json:"column_2"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) SearchExamsBySubject(ctx context.Context, arg SearchExamsBySubjectParams) ([]Exam, error) {
	rows, err := q.db.Query(ctx, searchExamsBySubject,
		arg.SubjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.TotalMarks,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExam = `-- name: SoftDeleteExam :exec
UPDATE exams SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteExam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteExam, id)
	return err
}

const startExamAttempt = `-- name: StartExamAttempt :one
INSERT INTO exam_attempts (exam_id, student_id)
VALUES ($1, $2)
RETURNING id, exam_id, student_id, started_at, submitted_at, score, status, created_at
`

type StartExamAttemptParams struct {
	ExamID    uuid.NullUUID `json:"exam_id"`
	StudentID uuid.NullUUID `json:"student_id"`
}

func (q *Queries) StartExamAttempt(ctx context.Context, arg StartExamAttemptParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, startExamAttempt, arg.ExamID, arg.StudentID)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const submitExamAttempt = `-- name: SubmitExamAttempt :exec
UPDATE exam_attempts
SET submitted_at = NOW(), status = 'SUBMITTED', score = $1
WHERE id = $2
`

type SubmitExamAttemptParams struct {
	Score pgtype.Int4 `json:"score"`
	ID    uuid.UUID   `json:"id"`
}

func (q *Queries) SubmitExamAttempt(ctx context.Context, arg SubmitExamAttemptParams) error {
	_, err := q.db.Exec(ctx, submitExamAttempt, arg.Score, arg.ID)
	return err
}

const updateExam = `-- name: UpdateExam :one
UPDATE exams
SET 
  title = $2,
  description = $3,
  total_marks = $4,
  status = $5
WHERE id = $1
RETURNING id, subject_id, title, description, total_marks, status, created_by, created_at, updated_at, deleted_at
`

type UpdateExamParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description *string        `json:"description"`
	TotalMarks  int32          `json:"total_marks"`
	Status      ExamStatusType `json:"status"`
}

func (q *Queries) UpdateExam(ctx context.Context, arg UpdateExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, updateExam,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TotalMarks,
		arg.Status,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.TotalMarks,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
