// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChoice = `-- name: CreateChoice :one
INSERT INTO choices (question_id, choice_text, is_correct)
VALUES ($1, $2, $3)
RETURNING id, question_id, choice_text, is_correct
`

type CreateChoiceParams struct {
	QuestionID uuid.NullUUID `json:"question_id"`
	ChoiceText string        `json:"choice_text"`
	IsCorrect  bool          `json:"is_correct"`
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error) {
	row := q.db.QueryRow(ctx, createChoice, arg.QuestionID, arg.ChoiceText, arg.IsCorrect)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ChoiceText,
		&i.IsCorrect,
	)
	return i, err
}

const createExam = `-- name: CreateExam :one
INSERT INTO exams (subject_id, title, description, duration_minutes, total_marks, start_time, end_time, status, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, subject_id, title, description, duration_minutes, total_marks, start_time, end_time, status, created_by, created_at, updated_at, deleted_at
`

type CreateExamParams struct {
	SubjectID       uuid.NullUUID    `json:"subject_id"`
	Title           string           `json:"title"`
	Description     *string          `json:"description"`
	DurationMinutes int32            `json:"duration_minutes"`
	TotalMarks      int32            `json:"total_marks"`
	StartTime       pgtype.Timestamp `json:"start_time"`
	EndTime         pgtype.Timestamp `json:"end_time"`
	Status          ExamStatusType   `json:"status"`
	CreatedBy       uuid.NullUUID    `json:"created_by"`
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, createExam,
		arg.SubjectID,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.TotalMarks,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.CreatedBy,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.TotalMarks,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (exam_id, question_text, marks, position)
VALUES ($1, $2, $3, $4)
RETURNING id, exam_id, question_text, marks, position, created_at
`

type CreateQuestionParams struct {
	ExamID       uuid.NullUUID `json:"exam_id"`
	QuestionText string        `json:"question_text"`
	Marks        int32         `json:"marks"`
	Position     int32         `json:"position"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ExamID,
		arg.QuestionText,
		arg.Marks,
		arg.Position,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.QuestionText,
		&i.Marks,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, exam_id, student_id, started_at, submitted_at, score, status, created_at FROM exam_attempts WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getExamByID = `-- name: GetExamByID :one
SELECT id, subject_id, title, description, duration_minutes, total_marks, start_time, end_time, status, created_by, created_at, updated_at, deleted_at FROM exams WHERE id = $1
`

func (q *Queries) GetExamByID(ctx context.Context, id uuid.UUID) (Exam, error) {
	row := q.db.QueryRow(ctx, getExamByID, id)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.TotalMarks,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAnswersByAttempt = `-- name: ListAnswersByAttempt :many
SELECT id, attempt_id, question_id, selected_choice_id, is_correct, answered_at FROM student_answers WHERE attempt_id = $1
`

func (q *Queries) ListAnswersByAttempt(ctx context.Context, attemptID uuid.NullUUID) ([]StudentAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentAnswer
	for rows.Next() {
		var i StudentAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.SelectedChoiceID,
			&i.IsCorrect,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByStudent = `-- name: ListAttemptsByStudent :many
SELECT id, exam_id, student_id, started_at, submitted_at, score, status, created_at FROM exam_attempts WHERE student_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListAttemptsByStudent(ctx context.Context, studentID uuid.NullUUID) ([]ExamAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExamAttempt
	for rows.Next() {
		var i ExamAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.StudentID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChoicesByQuestion = `-- name: ListChoicesByQuestion :many
SELECT id, question_id, choice_text, is_correct FROM choices WHERE question_id = $1
`

func (q *Queries) ListChoicesByQuestion(ctx context.Context, questionID uuid.NullUUID) ([]Choice, error) {
	rows, err := q.db.Query(ctx, listChoicesByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choice
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ChoiceText,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsBySubject = `-- name: ListExamsBySubject :many
SELECT id, subject_id, title, description, duration_minutes, total_marks, start_time, end_time, status, created_by, created_at, updated_at, deleted_at FROM exams WHERE subject_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExamsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.TotalMarks,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByExam = `-- name: ListQuestionsByExam :many
SELECT id, exam_id, question_text, marks, position, created_at FROM questions WHERE exam_id = $1 ORDER BY position ASC
`

func (q *Queries) ListQuestionsByExam(ctx context.Context, examID uuid.NullUUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.QuestionText,
			&i.Marks,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAnswer = `-- name: SaveAnswer :one
INSERT INTO student_answers (attempt_id, question_id, selected_choice_id, is_correct)
VALUES ($1, $2, $3, $4)
RETURNING id, attempt_id, question_id, selected_choice_id, is_correct, answered_at
`

type SaveAnswerParams struct {
	AttemptID        uuid.NullUUID `json:"attempt_id"`
	QuestionID       uuid.NullUUID `json:"question_id"`
	SelectedChoiceID uuid.NullUUID `json:"selected_choice_id"`
	IsCorrect        pgtype.Bool   `json:"is_correct"`
}

func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) (StudentAnswer, error) {
	row := q.db.QueryRow(ctx, saveAnswer,
		arg.AttemptID,
		arg.QuestionID,
		arg.SelectedChoiceID,
		arg.IsCorrect,
	)
	var i StudentAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.SelectedChoiceID,
		&i.IsCorrect,
		&i.AnsweredAt,
	)
	return i, err
}

const startExamAttempt = `-- name: StartExamAttempt :one
INSERT INTO exam_attempts (exam_id, student_id)
VALUES ($1, $2)
RETURNING id, exam_id, student_id, started_at, submitted_at, score, status, created_at
`

type StartExamAttemptParams struct {
	ExamID    uuid.NullUUID `json:"exam_id"`
	StudentID uuid.NullUUID `json:"student_id"`
}

func (q *Queries) StartExamAttempt(ctx context.Context, arg StartExamAttemptParams) (ExamAttempt, error) {
	row := q.db.QueryRow(ctx, startExamAttempt, arg.ExamID, arg.StudentID)
	var i ExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const submitExamAttempt = `-- name: SubmitExamAttempt :exec
UPDATE exam_attempts
SET submitted_at = NOW(), status = 'SUBMITTED', score = $1
WHERE id = $2
`

type SubmitExamAttemptParams struct {
	Score pgtype.Int4 `json:"score"`
	ID    uuid.UUID   `json:"id"`
}

func (q *Queries) SubmitExamAttempt(ctx context.Context, arg SubmitExamAttemptParams) error {
	_, err := q.db.Exec(ctx, submitExamAttempt, arg.Score, arg.ID)
	return err
}
