// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptStatusType string

const (
	AttemptStatusTypeINPROGRESS AttemptStatusType = "IN_PROGRESS"
	AttemptStatusTypeSUBMITTED  AttemptStatusType = "SUBMITTED"
	AttemptStatusTypeGRADED     AttemptStatusType = "GRADED"
	AttemptStatusTypeCANCELLED  AttemptStatusType = "CANCELLED"
)

func (e *AttemptStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptStatusType(s)
	case string:
		*e = AttemptStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptStatusType: %T", src)
	}
	return nil
}

type NullAttemptStatusType struct {
	AttemptStatusType AttemptStatusType `json:"attempt_status_type"`
	Valid             bool              `json:"valid"` // Valid is true if AttemptStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptStatusType), nil
}

type ExamStatusType string

const (
	ExamStatusTypeDRAFT     ExamStatusType = "DRAFT"
	ExamStatusTypePUBLISHED ExamStatusType = "PUBLISHED"
	ExamStatusTypeCLOSED    ExamStatusType = "CLOSED"
)

func (e *ExamStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExamStatusType(s)
	case string:
		*e = ExamStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExamStatusType: %T", src)
	}
	return nil
}

type NullExamStatusType struct {
	ExamStatusType ExamStatusType `json:"exam_status_type"`
	Valid          bool           `json:"valid"` // Valid is true if ExamStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExamStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.ExamStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExamStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExamStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExamStatusType), nil
}

type QuestionTypeType string

const (
	QuestionTypeTypeTEXT  QuestionTypeType = "TEXT"
	QuestionTypeTypeCODE  QuestionTypeType = "CODE"
	QuestionTypeTypeIMAGE QuestionTypeType = "IMAGE"
)

func (e *QuestionTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionTypeType(s)
	case string:
		*e = QuestionTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionTypeType: %T", src)
	}
	return nil
}

type NullQuestionTypeType struct {
	QuestionTypeType QuestionTypeType `json:"question_type_type"`
	Valid            bool             `json:"valid"` // Valid is true if QuestionTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionTypeType), nil
}

type SubjectStatusType string

const (
	SubjectStatusTypeACTIVE    SubjectStatusType = "ACTIVE"
	SubjectStatusTypeINACTIVE  SubjectStatusType = "INACTIVE"
	SubjectStatusTypePUBLISHED SubjectStatusType = "PUBLISHED"
)

func (e *SubjectStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubjectStatusType(s)
	case string:
		*e = SubjectStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for SubjectStatusType: %T", src)
	}
	return nil
}

type NullSubjectStatusType struct {
	SubjectStatusType SubjectStatusType `json:"subject_status_type"`
	Valid             bool              `json:"valid"` // Valid is true if SubjectStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubjectStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.SubjectStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubjectStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubjectStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubjectStatusType), nil
}

type UserRoleType string

const (
	UserRoleTypeSTUDENT    UserRoleType = "STUDENT"
	UserRoleTypeINSTRUCTOR UserRoleType = "INSTRUCTOR"
	UserRoleTypeADMIN      UserRoleType = "ADMIN"
)

func (e *UserRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleType(s)
	case string:
		*e = UserRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleType: %T", src)
	}
	return nil
}

type NullUserRoleType struct {
	UserRoleType UserRoleType `json:"user_role_type"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleType), nil
}

type Choice struct {
	ID         uuid.UUID          `json:"id"`
	QuestionID uuid.NullUUID      `json:"question_id"`
	ChoiceText string             `json:"choice_text"`
	IsCorrect  bool               `json:"is_correct"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Enrollment struct {
	ID         uuid.UUID          `json:"id"`
	StudentID  uuid.NullUUID      `json:"student_id"`
	ExamID     uuid.NullUUID      `json:"exam_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type Exam struct {
	ID          uuid.UUID          `json:"id"`
	SubjectID   uuid.NullUUID      `json:"subject_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	TotalMarks  float64            `json:"total_marks"`
	Status      ExamStatusType     `json:"status"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	PassScore   float64            `json:"pass_score"`
}

type ExamAttempt struct {
	ID          uuid.UUID          `json:"id"`
	ExamID      uuid.NullUUID      `json:"exam_id"`
	StudentID   uuid.NullUUID      `json:"student_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	Score       pgtype.Float8      `json:"score"`
	Status      AttemptStatusType  `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Question struct {
	ID            uuid.UUID          `json:"id"`
	ExamID        uuid.NullUUID      `json:"exam_id"`
	QuestionTitle string             `json:"question_title"`
	QuestionText  string             `json:"question_text"`
	QuestionType  QuestionTypeType   `json:"question_type"`
	QuestionImage *string            `json:"question_image"`
	Checksum      *string            `json:"checksum"`
	Marks         float64            `json:"marks"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type StudentAnswer struct {
	ID               uuid.UUID          `json:"id"`
	AttemptID        uuid.NullUUID      `json:"attempt_id"`
	QuestionID       uuid.NullUUID      `json:"question_id"`
	SelectedChoiceID uuid.NullUUID      `json:"selected_choice_id"`
	IsCorrect        pgtype.Bool        `json:"is_correct"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

type Subject struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	Description     *string            `json:"description"`
	DurationMinutes int32              `json:"duration_minutes"`
	TotalMarks      float64            `json:"total_marks"`
	PassScore       float64            `json:"pass_score"`
	Status          SubjectStatusType  `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type SubjectInstructor struct {
	SubjectID    uuid.UUID          `json:"subject_id"`
	InstructorID uuid.UUID          `json:"instructor_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy   uuid.NullUUID      `json:"assigned_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SubjectStudent struct {
	SubjectID  uuid.UUID          `json:"subject_id"`
	StudentID  uuid.UUID          `json:"student_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy uuid.NullUUID      `json:"assigned_by"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	FullName     string             `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRoleType       `json:"role"`
	IsActive     bool               `json:"is_active"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
