// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptStatusType string

const (
	AttemptStatusTypeINPROGRESS AttemptStatusType = "IN_PROGRESS"
	AttemptStatusTypeSUBMITTED  AttemptStatusType = "SUBMITTED"
	AttemptStatusTypeGRADED     AttemptStatusType = "GRADED"
	AttemptStatusTypeCANCELLED  AttemptStatusType = "CANCELLED"
)

func (e *AttemptStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptStatusType(s)
	case string:
		*e = AttemptStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptStatusType: %T", src)
	}
	return nil
}

type NullAttemptStatusType struct {
	AttemptStatusType AttemptStatusType `json:"attempt_status_type"`
	Valid             bool              `json:"valid"` // Valid is true if AttemptStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptStatusType), nil
}

type ExamStatusType string

const (
	ExamStatusTypeDRAFT     ExamStatusType = "DRAFT"
	ExamStatusTypePUBLISHED ExamStatusType = "PUBLISHED"
	ExamStatusTypeCLOSED    ExamStatusType = "CLOSED"
)

func (e *ExamStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExamStatusType(s)
	case string:
		*e = ExamStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExamStatusType: %T", src)
	}
	return nil
}

type NullExamStatusType struct {
	ExamStatusType ExamStatusType `json:"exam_status_type"`
	Valid          bool           `json:"valid"` // Valid is true if ExamStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExamStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.ExamStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExamStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExamStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExamStatusType), nil
}

type UserRoleType string

const (
	UserRoleTypeSTUDENT    UserRoleType = "STUDENT"
	UserRoleTypeINSTRUCTOR UserRoleType = "INSTRUCTOR"
	UserRoleTypeADMIN      UserRoleType = "ADMIN"
)

func (e *UserRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleType(s)
	case string:
		*e = UserRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleType: %T", src)
	}
	return nil
}

type NullUserRoleType struct {
	UserRoleType UserRoleType `json:"user_role_type"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleType), nil
}

type Choice struct {
	ID         uuid.UUID     `json:"id"`
	QuestionID uuid.NullUUID `json:"question_id"`
	ChoiceText string        `json:"choice_text"`
	IsCorrect  bool          `json:"is_correct"`
}

type Enrollment struct {
	ID         uuid.UUID          `json:"id"`
	StudentID  uuid.NullUUID      `json:"student_id"`
	ExamID     uuid.NullUUID      `json:"exam_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type Exam struct {
	ID              uuid.UUID          `json:"id"`
	SubjectID       uuid.NullUUID      `json:"subject_id"`
	Title           string             `json:"title"`
	Description     *string            `json:"description"`
	DurationMinutes int32              `json:"duration_minutes"`
	TotalMarks      int32              `json:"total_marks"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Status          ExamStatusType     `json:"status"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ExamAttempt struct {
	ID          uuid.UUID          `json:"id"`
	ExamID      uuid.NullUUID      `json:"exam_id"`
	StudentID   uuid.NullUUID      `json:"student_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	Score       pgtype.Int4        `json:"score"`
	Status      AttemptStatusType  `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Question struct {
	ID           uuid.UUID          `json:"id"`
	ExamID       uuid.NullUUID      `json:"exam_id"`
	QuestionText string             `json:"question_text"`
	Marks        int32              `json:"marks"`
	Position     int32              `json:"position"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type StudentAnswer struct {
	ID               uuid.UUID          `json:"id"`
	AttemptID        uuid.NullUUID      `json:"attempt_id"`
	QuestionID       uuid.NullUUID      `json:"question_id"`
	SelectedChoiceID uuid.NullUUID      `json:"selected_choice_id"`
	IsCorrect        pgtype.Bool        `json:"is_correct"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

type Subject struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type SubjectInstructor struct {
	SubjectID    uuid.UUID          `json:"subject_id"`
	InstructorID uuid.UUID          `json:"instructor_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy   uuid.NullUUID      `json:"assigned_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	FullName     string             `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRoleType       `json:"role"`
	IsActive     bool               `json:"is_active"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
