// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignInstructorToSubject(ctx context.Context, arg AssignInstructorToSubjectParams) (SubjectInstructor, error)
	AssignStudentToSubject(ctx context.Context, arg AssignStudentToSubjectParams) (SubjectStudent, error)
	ClosePublishedExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) error
	CloseSubject(ctx context.Context, id uuid.UUID) error
	CountDeletedSubjects(ctx context.Context) (int64, error)
	CountDeletedUsers(ctx context.Context) (int64, error)
	CountExams(ctx context.Context) (int64, error)
	CountExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) (int64, error)
	CountInstructors(ctx context.Context) (int64, error)
	CountPublishedExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) (int64, error)
	CountQuestions(ctx context.Context) (int64, error)
	CountSearchDeletedUsers(ctx context.Context, search string) (int64, error)
	CountSearchExams(ctx context.Context, dollar_1 string) (int64, error)
	CountSearchExamsBySubject(ctx context.Context, arg CountSearchExamsBySubjectParams) (int64, error)
	CountSearchStudentsBySubjectID(ctx context.Context, arg CountSearchStudentsBySubjectIDParams) (int64, error)
	CountSearchSubjects(ctx context.Context, title *string) (int64, error)
	CountSearchUsers(ctx context.Context, search string) (int64, error)
	CountStudents(ctx context.Context) (int64, error)
	CountStudentsBySubjectID(ctx context.Context, subjectID uuid.UUID) (int64, error)
	CountSubjects(ctx context.Context) (int64, error)
	CountSubmittedAttemptsBySubjectForStudent(ctx context.Context, arg CountSubmittedAttemptsBySubjectForStudentParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error)
	CreateChoices(ctx context.Context, arg CreateChoicesParams) ([]Choice, error)
	CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteChoicesByQuestion(ctx context.Context, questionID uuid.NullUUID) error
	DeleteQuestionByID(ctx context.Context, id uuid.UUID) error
	DeleteSubject(ctx context.Context, id uuid.UUID) (Subject, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DisableUser(ctx context.Context, id uuid.UUID) error
	EnableUser(ctx context.Context, id uuid.UUID) error
	GetAttemptByExamAndStudent(ctx context.Context, arg GetAttemptByExamAndStudentParams) (ExamAttempt, error)
	GetAttemptByID(ctx context.Context, id uuid.UUID) (ExamAttempt, error)
	GetExamByID(ctx context.Context, id uuid.UUID) (Exam, error)
	GetQuestionByChecksum(ctx context.Context, checksum *string) (Question, error)
	GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error)
	GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListAllExams(ctx context.Context, arg ListAllExamsParams) ([]Exam, error)
	ListAllInstructors(ctx context.Context, arg ListAllInstructorsParams) ([]User, error)
	ListAllStudents(ctx context.Context, arg ListAllStudentsParams) ([]User, error)
	ListAllSubjects(ctx context.Context, arg ListAllSubjectsParams) ([]Subject, error)
	ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error)
	ListAnswersByAttempt(ctx context.Context, attemptID uuid.NullUUID) ([]StudentAnswer, error)
	ListAttemptsByStudent(ctx context.Context, studentID uuid.NullUUID) ([]ExamAttempt, error)
	ListChoicesByQuestion(ctx context.Context, questionID uuid.NullUUID) ([]Choice, error)
	ListChoicesByQuestionSeeded(ctx context.Context, arg ListChoicesByQuestionSeededParams) ([]Choice, error)
	ListDeletedSubjects(ctx context.Context, arg ListDeletedSubjectsParams) ([]Subject, error)
	ListDeletedUsers(ctx context.Context, arg ListDeletedUsersParams) ([]User, error)
	ListExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) ([]Exam, error)
	ListExamsCreatedBy(ctx context.Context, createdBy uuid.NullUUID) ([]Exam, error)
	ListExamsForStudent(ctx context.Context, studentID uuid.UUID) ([]Exam, error)
	ListInstructorsBySubjectID(ctx context.Context, subjectID uuid.UUID) ([]ListInstructorsBySubjectIDRow, error)
	ListQuestionsByExam(ctx context.Context, examID uuid.NullUUID) ([]Question, error)
	ListStudentsBySubjectID(ctx context.Context, subjectID uuid.UUID) ([]ListStudentsBySubjectIDRow, error)
	ListStudentsBySubjectIDPaginated(ctx context.Context, arg ListStudentsBySubjectIDPaginatedParams) ([]ListStudentsBySubjectIDPaginatedRow, error)
	ListSubjectsForStudent(ctx context.Context, studentID uuid.UUID) ([]Subject, error)
	ListUsersByRole(ctx context.Context, role UserRoleType) ([]User, error)
	PublishDraftExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) error
	PublishSubject(ctx context.Context, id uuid.UUID) error
	RestoreQuestion(ctx context.Context, id uuid.UUID) error
	RestoreSubject(ctx context.Context, id uuid.UUID) (Subject, error)
	RestoreUser(ctx context.Context, id uuid.UUID) error
	SaveAnswer(ctx context.Context, arg SaveAnswerParams) (StudentAnswer, error)
	SearchDeletedUsers(ctx context.Context, arg SearchDeletedUsersParams) ([]User, error)
	SearchExams(ctx context.Context, arg SearchExamsParams) ([]Exam, error)
	SearchExamsBySubject(ctx context.Context, arg SearchExamsBySubjectParams) ([]Exam, error)
	SearchStudents(ctx context.Context, arg SearchStudentsParams) ([]User, error)
	SearchStudentsBySubjectID(ctx context.Context, arg SearchStudentsBySubjectIDParams) ([]SearchStudentsBySubjectIDRow, error)
	SearchSubjects(ctx context.Context, arg SearchSubjectsParams) ([]Subject, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetQuestionImagePath(ctx context.Context, arg SetQuestionImagePathParams) error
	SoftDeleteExam(ctx context.Context, id uuid.UUID) error
	SoftDeleteInstructorsBySubject(ctx context.Context, subjectID uuid.UUID) error
	SoftDeleteQuestion(ctx context.Context, id uuid.UUID) error
	SoftDeleteSubject(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	StartExamAttempt(ctx context.Context, arg StartExamAttemptParams) (ExamAttempt, error)
	SubmitExamAttempt(ctx context.Context, arg SubmitExamAttemptParams) error
	UnassignInstructorFromSubject(ctx context.Context, arg UnassignInstructorFromSubjectParams) (SubjectInstructor, error)
	UnassignStudentFromSubject(ctx context.Context, arg UnassignStudentFromSubjectParams) (SubjectStudent, error)
	UpdateExam(ctx context.Context, arg UpdateExamParams) (Exam, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
