// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error)
	CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EnrollStudent(ctx context.Context, arg EnrollStudentParams) (Enrollment, error)
	GetAttemptByID(ctx context.Context, id uuid.UUID) (ExamAttempt, error)
	GetEnrollmentsByStudent(ctx context.Context, studentID uuid.NullUUID) ([]Enrollment, error)
	GetExamByID(ctx context.Context, id uuid.UUID) (Exam, error)
	GetStudentsInSubject(ctx context.Context, subjectID uuid.NullUUID) ([]uuid.NullUUID, error)
	GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]UserRoleType, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListAnswersByAttempt(ctx context.Context, attemptID uuid.NullUUID) ([]StudentAnswer, error)
	ListAttemptsByStudent(ctx context.Context, studentID uuid.NullUUID) ([]ExamAttempt, error)
	ListChoicesByQuestion(ctx context.Context, questionID uuid.NullUUID) ([]Choice, error)
	ListExamsBySubject(ctx context.Context, subjectID uuid.NullUUID) ([]Exam, error)
	ListQuestionsByExam(ctx context.Context, examID uuid.NullUUID) ([]Question, error)
	ListSubjectsByInstructor(ctx context.Context, instructorID uuid.NullUUID) ([]Subject, error)
	SaveAnswer(ctx context.Context, arg SaveAnswerParams) (StudentAnswer, error)
	StartExamAttempt(ctx context.Context, arg StartExamAttemptParams) (ExamAttempt, error)
	SubmitExamAttempt(ctx context.Context, arg SubmitExamAttemptParams) error
}

var _ Querier = (*Queries)(nil)
