// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countQuestions = `-- name: CountQuestions :one
SELECT COUNT(*) FROM questions WHERE deleted_at IS NULL
`

func (q *Queries) CountQuestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChoice = `-- name: CreateChoice :one
INSERT INTO choices (question_id, choice_text, is_correct)
VALUES ($1, $2, $3)
RETURNING id, question_id, choice_text, is_correct, created_at, updated_at, deleted_at
`

type CreateChoiceParams struct {
	QuestionID uuid.NullUUID `json:"question_id"`
	ChoiceText string        `json:"choice_text"`
	IsCorrect  bool          `json:"is_correct"`
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error) {
	row := q.db.QueryRow(ctx, createChoice, arg.QuestionID, arg.ChoiceText, arg.IsCorrect)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ChoiceText,
		&i.IsCorrect,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createChoices = `-- name: CreateChoices :many
INSERT INTO choices (question_id, choice_text, is_correct)
VALUES ($1, $2, $3)
RETURNING id, question_id, choice_text, is_correct, created_at, updated_at, deleted_at
`

type CreateChoicesParams struct {
	QuestionID uuid.NullUUID `json:"question_id"`
	ChoiceText string        `json:"choice_text"`
	IsCorrect  bool          `json:"is_correct"`
}

func (q *Queries) CreateChoices(ctx context.Context, arg CreateChoicesParams) ([]Choice, error) {
	rows, err := q.db.Query(ctx, createChoices, arg.QuestionID, arg.ChoiceText, arg.IsCorrect)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choice
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (exam_id, question_title, question_text, question_type, marks, question_image, checksum)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, exam_id, question_title, question_text, question_type, question_image, checksum, marks, created_at, updated_at, deleted_at
`

type CreateQuestionParams struct {
	ExamID        uuid.NullUUID    `json:"exam_id"`
	QuestionTitle string           `json:"question_title"`
	QuestionText  string           `json:"question_text"`
	QuestionType  QuestionTypeType `json:"question_type"`
	Marks         float64          `json:"marks"`
	QuestionImage *string          `json:"question_image"`
	Checksum      *string          `json:"checksum"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ExamID,
		arg.QuestionTitle,
		arg.QuestionText,
		arg.QuestionType,
		arg.Marks,
		arg.QuestionImage,
		arg.Checksum,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.QuestionTitle,
		&i.QuestionText,
		&i.QuestionType,
		&i.QuestionImage,
		&i.Checksum,
		&i.Marks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteChoicesByQuestion = `-- name: DeleteChoicesByQuestion :exec
UPDATE choices SET deleted_at = NOW() WHERE question_id = $1
`

func (q *Queries) DeleteChoicesByQuestion(ctx context.Context, questionID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteChoicesByQuestion, questionID)
	return err
}

const deleteQuestionByID = `-- name: DeleteQuestionByID :exec
UPDATE questions SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteQuestionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestionByID, id)
	return err
}

const getQuestionByChecksum = `-- name: GetQuestionByChecksum :one
SELECT id, exam_id, question_title, question_text, question_type, question_image, checksum, marks, created_at, updated_at, deleted_at FROM questions WHERE deleted_at IS NULL AND checksum = $1
`

func (q *Queries) GetQuestionByChecksum(ctx context.Context, checksum *string) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByChecksum, checksum)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.QuestionTitle,
		&i.QuestionText,
		&i.QuestionType,
		&i.QuestionImage,
		&i.Checksum,
		&i.Marks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, exam_id, question_title, question_text, question_type, question_image, checksum, marks, created_at, updated_at, deleted_at FROM questions WHERE deleted_at IS NULL AND id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.QuestionTitle,
		&i.QuestionText,
		&i.QuestionType,
		&i.QuestionImage,
		&i.Checksum,
		&i.Marks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllChoicesByQuestion = `-- name: ListAllChoicesByQuestion :many
SELECT id, question_id, choice_text, is_correct, created_at, updated_at, deleted_at FROM choices WHERE question_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAllChoicesByQuestion(ctx context.Context, questionID uuid.NullUUID) ([]Choice, error) {
	rows, err := q.db.Query(ctx, listAllChoicesByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choice
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChoicesByQuestion = `-- name: ListChoicesByQuestion :many
SELECT id, question_id, choice_text, is_correct, created_at, updated_at, deleted_at FROM choices WHERE deleted_at IS NULL AND question_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListChoicesByQuestion(ctx context.Context, questionID uuid.NullUUID) ([]Choice, error) {
	rows, err := q.db.Query(ctx, listChoicesByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choice
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChoicesByQuestionSeeded = `-- name: ListChoicesByQuestionSeeded :many
SELECT id, question_id, choice_text, is_correct, created_at, updated_at, deleted_at FROM choices 
WHERE deleted_at IS NULL 
  AND question_id = $1 
ORDER BY md5(id::text || $2::text)
`

type ListChoicesByQuestionSeededParams struct {
	QuestionID uuid.NullUUID `json:"question_id"`
	Column2    string        `json:"column_2"`
}

func (q *Queries) ListChoicesByQuestionSeeded(ctx context.Context, arg ListChoicesByQuestionSeededParams) ([]Choice, error) {
	rows, err := q.db.Query(ctx, listChoicesByQuestionSeeded, arg.QuestionID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choice
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ChoiceText,
			&i.IsCorrect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByExam = `-- name: ListQuestionsByExam :many
SELECT id, exam_id, question_title, question_text, question_type, question_image, checksum, marks, created_at, updated_at, deleted_at FROM questions WHERE deleted_at IS NULL AND exam_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListQuestionsByExam(ctx context.Context, examID uuid.NullUUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.QuestionTitle,
			&i.QuestionText,
			&i.QuestionType,
			&i.QuestionImage,
			&i.Checksum,
			&i.Marks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreQuestion = `-- name: RestoreQuestion :exec
UPDATE questions SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestoreQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreQuestion, id)
	return err
}

const setQuestionImagePath = `-- name: SetQuestionImagePath :exec
UPDATE questions SET question_image = $2 WHERE deleted_at IS NULL AND question_type = 'IMAGE' AND id = $1
`

type SetQuestionImagePathParams struct {
	ID            uuid.UUID `json:"id"`
	QuestionImage *string   `json:"question_image"`
}

func (q *Queries) SetQuestionImagePath(ctx context.Context, arg SetQuestionImagePathParams) error {
	_, err := q.db.Exec(ctx, setQuestionImagePath, arg.ID, arg.QuestionImage)
	return err
}

const softDeleteChoiceByID = `-- name: SoftDeleteChoiceByID :exec
UPDATE choices SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteChoiceByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteChoiceByID, id)
	return err
}

const softDeleteQuestion = `-- name: SoftDeleteQuestion :exec
UPDATE questions SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteQuestion, id)
	return err
}

const updateChoice = `-- name: UpdateChoice :one
UPDATE choices
SET choice_text = $2, is_correct = $3, deleted_at = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, question_id, choice_text, is_correct, created_at, updated_at, deleted_at
`

type UpdateChoiceParams struct {
	ID         uuid.UUID `json:"id"`
	ChoiceText string    `json:"choice_text"`
	IsCorrect  bool      `json:"is_correct"`
}

func (q *Queries) UpdateChoice(ctx context.Context, arg UpdateChoiceParams) (Choice, error) {
	row := q.db.QueryRow(ctx, updateChoice, arg.ID, arg.ChoiceText, arg.IsCorrect)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ChoiceText,
		&i.IsCorrect,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET 
  question_title = $2,
  question_text = $3,
  question_type = $4,
  marks = $5,
  question_image = $6
WHERE id = $1
RETURNING id, exam_id, question_title, question_text, question_type, question_image, checksum, marks, created_at, updated_at, deleted_at
`

type UpdateQuestionParams struct {
	ID            uuid.UUID        `json:"id"`
	QuestionTitle string           `json:"question_title"`
	QuestionText  string           `json:"question_text"`
	QuestionType  QuestionTypeType `json:"question_type"`
	Marks         float64          `json:"marks"`
	QuestionImage *string          `json:"question_image"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.QuestionTitle,
		arg.QuestionText,
		arg.QuestionType,
		arg.Marks,
		arg.QuestionImage,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.QuestionTitle,
		&i.QuestionText,
		&i.QuestionType,
		&i.QuestionImage,
		&i.Checksum,
		&i.Marks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
