// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subject.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (title, description)
VALUES ($1, $2)
RETURNING id, title, description, created_at, updated_at, deleted_at
`

type CreateSubjectParams struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.Title, arg.Description)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, title, description, created_at, updated_at, deleted_at FROM subjects WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllSubjects = `-- name: ListAllSubjects :many
SELECT id, title, description, created_at, updated_at, deleted_at FROM subjects WHERE deleted_at IS NULL
`

func (q *Queries) ListAllSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listAllSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubjects = `-- name: SearchSubjects :many
SELECT id, title, description, created_at, updated_at, deleted_at FROM subjects WHERE title ILIKE '%' || $1::text || '%' AND deleted_at IS NULL
`

func (q *Queries) SearchSubjects(ctx context.Context, dollar_1 string) ([]Subject, error) {
	rows, err := q.db.Query(ctx, searchSubjects, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
