// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countDeletedUsers = `-- name: CountDeletedUsers :one
SELECT count(*) FROM users 
WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountDeletedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeletedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInstructors = `-- name: CountInstructors :one
SELECT count(*) FROM users 
WHERE role = 'INSTRUCTOR' AND deleted_at IS NULL
`

func (q *Queries) CountInstructors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstructors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchDeletedUsers = `-- name: CountSearchDeletedUsers :one
SELECT count(*) FROM users
WHERE 
    deleted_at IS NOT NULL 
    AND (
        username ILIKE '%' || $1::text || '%'
        OR full_name ILIKE '%' || $1::text || '%'
    )
`

func (q *Queries) CountSearchDeletedUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchDeletedUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT count(*) FROM users
WHERE 
    deleted_at IS NULL 
    AND (
        username ILIKE '%' || $1::text || '%'
        OR full_name ILIKE '%' || $1::text || '%'
    )
`

func (q *Queries) CountSearchUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudents = `-- name: CountStudents :one
SELECT count(*) FROM users 
WHERE role = 'STUDENT' AND deleted_at IS NULL
`

func (q *Queries) CountStudents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users 
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    full_name,
    password_hash,
    role,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username     string       `json:"username"`
	FullName     string       `json:"full_name"`
	PasswordHash string       `json:"password_hash"`
	Role         UserRoleType `json:"role"`
	IsActive     bool         `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users 
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users 
SET is_active = false
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DisableUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUser, id)
	return err
}

const enableUser = `-- name: EnableUser :exec
UPDATE users 
SET is_active = true
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) EnableUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE is_active = TRUE AND deleted_at IS NULL 
ORDER BY created_at DESC
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllInstructors = `-- name: ListAllInstructors :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE role = 'INSTRUCTOR' AND deleted_at IS NULL
ORDER BY last_login DESC NULLS LAST, id ASC
LIMIT $1 OFFSET $2
`

type ListAllInstructorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllInstructors(ctx context.Context, arg ListAllInstructorsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllInstructors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStudents = `-- name: ListAllStudents :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE role = 'STUDENT' AND deleted_at IS NULL
ORDER BY last_login DESC NULLS LAST, id ASC
LIMIT $1 OFFSET $2
`

type ListAllStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllStudents(ctx context.Context, arg ListAllStudentsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE deleted_at IS NULL 
ORDER BY last_login DESC NULLS LAST, id ASC
LIMIT $1 OFFSET $2
`

type ListAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedUsers = `-- name: ListDeletedUsers :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE deleted_at IS NOT NULL 
ORDER BY deleted_at DESC, id ASC
LIMIT $1 OFFSET $2
`

type ListDeletedUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDeletedUsers(ctx context.Context, arg ListDeletedUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listDeletedUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users 
WHERE role = $1 AND deleted_at IS NULL 
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByRole(ctx context.Context, role UserRoleType) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users 
SET deleted_at = NULL, is_active = true
WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const searchDeletedUsers = `-- name: SearchDeletedUsers :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users
WHERE 
    deleted_at IS NOT NULL 
    AND (
        username ILIKE '%' || $3::text || '%'
        OR full_name ILIKE '%' || $3::text || '%'
    )
ORDER BY deleted_at DESC, id ASC
LIMIT $1 OFFSET $2
`

type SearchDeletedUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) SearchDeletedUsers(ctx context.Context, arg SearchDeletedUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchDeletedUsers, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStudents = `-- name: SearchStudents :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users
WHERE 
    deleted_at IS NULL 
    AND role = 'STUDENT'
    AND (
        username ILIKE '%' || $3::text || '%'
        OR full_name ILIKE '%' || $3::text || '%'
    )
ORDER BY last_login DESC NULLS LAST, id ASC
LIMIT $1 OFFSET $2
`

type SearchStudentsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) SearchStudents(ctx context.Context, arg SearchStudentsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchStudents, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at FROM users
WHERE 
    deleted_at IS NULL 
    AND (
        username ILIKE '%' || $3::text || '%'
        OR full_name ILIKE '%' || $3::text || '%'
    )
ORDER BY last_login DESC NULLS LAST, id ASC
LIMIT $1 OFFSET $2
`

type SearchUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users 
SET deleted_at = NOW(), is_active = false
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users 
SET username = $2, 
    full_name = $3, 
    role = $4, 
    is_active = $5,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, full_name, password_hash, role, is_active, last_login, created_at, updated_at, deleted_at
`

type UpdateUserInfoParams struct {
	ID       uuid.UUID    `json:"id"`
	Username string       `json:"username"`
	FullName string       `json:"full_name"`
	Role     UserRoleType `json:"role"`
	IsActive bool         `json:"is_active"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInfo,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users 
SET last_login = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users 
SET password_hash = $2, 
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users 
SET role = $2 
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID    `json:"id"`
	Role UserRoleType `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
